/* FUNCOES DE AGREGACAO */

/*QUERY SIMPLES*/

SELECT * FROM FUNCIONARIOS;

/* CONTANDO O NUMERO DE OCORRENCIAS */

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT COUNT(*) FROM LOCALIZACAO;

/* AGRUPANDO POR  GROUP BY */

SELECT COUNT(*) 
FROM FUNCIONARIOS
GROUP BY SEXO;
 
/* COLOCANDO O NOME DA COLUNA */

SELECT SEXO, COUNT(*) AS "QUANTIDADE"  
FROM FUNCIONARIOS
GROUP BY SEXO;

/* MOSTRANDO O NUMERO DE FUNCIONARIOS EM CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, COUNT(*)
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MAXIMO DE SALARIOS - 149929*/

SELECT MAX(SALARIO)
FROM FUNCIONARIOS;

/* EXIBINDO O MINIMO DE SALARIOS - 40138*/

SELECT MIN(SALARIO)
FROM FUNCIONARIOS;

/* EXIBINDO O MAXIMO E O MINIMO JUNTOS*/

SELECT MAX(SALARIO) AS "SALARIO MAXIMO",
	   MIN(SALARIO) AS "SALARIO MINIMO"
FROM FUNCIONARIOS;

/* EXIBINDO O MAXIMO E O MINIMO DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, MAX(SALARIO) AS "SALARIO MAXIMO",
	   MIN(SALARIO) AS "SALARIO MINIMO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MAXIMO E O MINIMO POR SEXO */

SELECT SEXO, MAX(SALARIO) AS "SALARIO MAXIMO",
	   MIN(SALARIO) AS "SALARIO MINIMO"
FROM FUNCIONARIOS
GROUP BY SEXO;

