/* Modelagem Básica */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PRECESSOS DE MODELAGEM */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - PRGRAMAS DE MODELAGEM
MODELAGEM FÍSICA - SCRIPTS DE BANCO