

/*sintaxe básica de inserção - INSERT INTO TABELA...*/
/*FORMA 01 - OMITINDO AS COLUNAS*/
INSERT INTO CLIENTE VALUES('KAUA', 'M', 'KAUAJARDIM2004@GMAIL.COM', 528177328, '963741027', 'CASA');

INSERT INTO CLIENTE VALUES('KAUA', 'M', 'KAUAJARDIM2004@GMAIL.COM', 1111, '22222', 'BRASIL - CIDADE - RIO - RJ');
/*FORMA 02 - ESPECIFICANDO AS COLUNAS*/
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE, EMAIL, CPF) VALUES('KAUA', 'M', 'CASA', '123456789', 'KAUA@GMAIL.COM', 52817732839); 

/*FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL*/

INSERT INTO CLIENTE VALUES('KAUA', 'M', 'JARDIM200@GMAIL.COM', 328528177, '145677655', 'SP'),
						  ('BIG', 'M', 'BIGAO@GMAIL.COM', 55577799, '658975623599', 'SAO PAULO');
						  
INSERT INTO CLIENTE VALUES('GABY', 'F', 'GABY@GMAIL.COM', 1235764, '4756498654', 'SP'),
						  ('MONTANARI', 'F', 'MONT@GMAIL.COM', 1264546, '547884654', 'SAO PAULO');	

INSERT INTO CLIENTE VALUES('XING', 'M', 'XING@GMAIL.COM', 51465, '94864516', 'BRASIL - SP - SAO PAULO'),
						  ('LING', 'F', 'LING@GMAIL.COM', 963545, '94678489', 'BRASIL - CIDADE - TOCA - SP');						  

/*O COMANDO SELECT
SELEÇÃO PROJEÇÃO E JUNÇÃO
*/
SELECT NOW() as DATA_HORA, 'KAUA JARDIM' as ALUNO;

SELECT 'KAUA JARDIM';

SELECT 'BANCO DE DADOS'; 

/*ALIAS DE COLUNAS*/
SELECT NOME as CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/*PARA FINS ACADEMICOS*/
SELECT * FROM CLIENTE;

/*FILTRANDO DADOS COM WHERE E LIKE*/
SELECT NOME, TELEFONE FROM CLIENTE;

/*UTILIZANDO WHERE*/
SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE ENDERECO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'SP';

/*UTILIZANDO LIKE*/

SELECT NOME, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'SP%';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CIDADE%';