DROP DATABASE AUTORELACIONAMENTO;

CREATE DATABASE AUTORELACIONAMENTO;

USE AUTORELACIONAMENTO;

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    HORAS INT,
    VALOR FLOAT(10,2),
    ID_PREREQ INT
);

ALTER TABLE CURSOS
ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

DESC CURSOS;

INSERT INTO CURSOS VALUES(NULL, 'BD RELACIONAL', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'BD BI', 40, 800.00, 1);
INSERT INTO CURSOS VALUES(NULL, 'LOGICA DE PROGRAMACAO C#', 60, 300.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'CURSO DE ORIENTAÇÃO C#', 55, 600.00, 3);
INSERT INTO CURSOS VALUES(NULL, 'ASP.NET', 30, 500.00, 4);

SELECT * FROM  CURSOS;

SELECT NOME, VALOR, IFNULL(ID_PREREQ, "SEM REQUISITOS") AS REQUISITO
FROM CURSOS;

SELECT  CUR.IDCURSO, CUR.NOME, CUR.VALOR, CUR.HORAS, IFNULL(PRE.NOME, "SEM REQUISITOS") AS "NOME DO REQUISITO"
FROM CURSOS CUR
    LEFT JOIN CURSOS PRE
    ON PRE.IDCURSO = CUR.ID_PREREQ;