DROP DATABASE CURSORES;
CREATE DATABASE CURSORES; 
USE CURSORES;

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT
);

INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('John Doe', 100, 150, 200);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Jane Smith', 120, 130, 110);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Bob Johnson', 200, 180, 160);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Emily Davis', 150, 140, 130);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Michael Brown', 110, 120, 130);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Jessica Wilson', 130, 140, 150);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('David Garcia', 180, 170, 160);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Daniel Martinez', 160, 150, 140);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Matthew Rodriguez', 140, 130, 120);
INSERT INTO VENDEDORES (NOME, JAN, FEV, MAR) VALUES ('Jacob Hernandez', 190, 200, 210);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL
FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL, TRUNCATE((JAN+FEV+MAR) / 3, 2) AS MEDIA
FROM VENDEDORES;

CREATE TABLE VENDA_TOTAL(
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER $
CREATE PROCEDURE INSEREDADOS()
BEGIN
    DECLARE FIM INT DEFAULT 0;
    DECLARE VJAN, VFEV, VMAR, VTOTAL, VMEDIA INT;
    DECLARE VNOME VARCHAR(50);

    DECLARE REGISTRO CURSOR FOR(
        SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
    );

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

    OPEN REGISTRO;

    REPEAT
 
    FETCH REGISTRO INTO VNOME, VJAN, VFEV, VMAR;
        IF NOT FIM THEN

            SET VTOTAL = VJAN + VFEV + VMAR;
            SET VMEDIA = VTOTAL / 3;

            INSERT INTO VENDA_TOTAL VALUES(VNOME, VJAN, VFEV, VMAR, VTOTAL, VMEDIA);

        END IF;

    UNTIL FIM END REPEAT;
    
    CLOSE REGISTRO;
END
$
DELIMITER ;

CALL INSEREDADOS();

SELECT * FROM  VENDA_TOTAL;