/*DELETANDO REGISTROS COM A CLAUSULA DELETE*/
USE PROJETO; 

SELECT COUNT(*) FROM CLIENTE; 
--TOTAL 9

SELECT COUNT(*) FROM CLIENTE 
WHERE NOME = 'KAUA';
--TOTAL DELETADO 4

DELETE FROM CLIENTE
WHERE NOME = 'KAUA';
 

SELECT COUNT(*) FROM CLIENTE; 

SELECT 9-4;

SELECT * FROM CLIENTE; 

INSERT INTO CLIENTE VALUES('XING', 'M', 'X.GARDEM@GMAIL.COM', 45638854, '4575-0048', 'RUA COPPER LEAF - WILLIAMSBURG - KITCHENER');

SELECT * FROM CLIENTE;

DELETE FROM CLIENTE 
WHERE NOME = 'XING'
AND EMAIL = 'X.GARDEM@GMAIL.COM';
--TRAZ APENAS O REGISTRO QUE SATISFACA TODAS AS CONDICOES

SELECT * FROM CLIENTE;