/*FILTRANDO VALORES NULOS*/
USE projeto;

/* UM VALOR NULO NÃO SE IGUALA A NADA POIS ELE É NULO/VAZIO
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL = NULL;
*/

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;

