USE COMERCIO;

CREATE TABLE ALUNOS(
    NUMERO INT,
    NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES(1, 'JOAO');
INSERT INTO ALUNOS VALUES(1, 'MARIA');
INSERT INTO ALUNOS VALUES(2, 'ZOE');
INSERT INTO ALUNOS VALUES(2, 'ANDRE');
INSERT INTO ALUNOS VALUES(3, 'CLARA');
INSERT INTO ALUNOS VALUES(1, 'CLARA');
INSERT INTO ALUNOS VALUES(4, 'KAUA');
INSERT INTO ALUNOS VALUES(5, 'GARDEN');
INSERT INTO ALUNOS VALUES(2, 'GABY');
INSERT INTO ALUNOS VALUES(4, 'LARISA');
INSERT INTO ALUNOS VALUES(5, 'ANA');
INSERT INTO ALUNOS VALUES(6, 'ANTONIO');
INSERT INTO ALUNOS VALUES(6, 'PAULA');

SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1; --ORDENA PRIMEIRA COLUNA

SELECT * FROM ALUNOS
ORDER BY 2; --ORDENA PELA SEGUNDA COLUNA

/* ORDENANDO POR MAIS DE UMA COLUNA */


SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;


SELECT * FROM ALUNOS
ORDER BY 1, 2;

/* MESCLANDO ORDER BY COM PROJECAO */

SELECT NOME
FROM ALUNOS
ORDER BY 1, 2;

SELECT NOME FROM ALUNOS
ORDER BY NUMERO, NOME; 

/* ORDER BY DESC / ASC */

SELECT * FROM ALUNOS
ORDER BY 1 ASC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC

SELECT * FROM ALUNOS
ORDER BY 1, 2 DESC;


SELECT * FROM ALUNOS
ORDER BY 1 DESC, 2 DESC;

/* ORDENANDO COM JOINS  */

SELECT C.NOME,
    C.SEXO,
    IFNULL (C.EMAIL, 'CLIENTE SEM EMAIL') AS "E-MAIL",
    T.TIPO,
    T.NUMERO,
    E.BAIRRO,
    E.CIDADE,
    E.UF
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 1;

/* ORDENANDO VIEW */
SELECT * FROM V_RELATORIO
ORDER BY 1;

