CREATE TABLE TB_EMPRESA(
ID INT,
NOME VARCHAR(50)
)
GO

/* CONECTANDO A UM BANCO */

USE EMPRESA
GO

/* CRIACAO DE TABELAS */


CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

/* CONSTRAINTS */

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('M','F'))
GO

/* 1 X 1 */

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL,
	CHECK (UF IN('RJ', 'SP', 'MG')),
	ID_ALUNO INT UNIQUE
)
GO

/* CRIANDO A FK */

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO)
REFERENCES ALUNO(IDALUNO)
GO

/* COMANDOS DE DESCRICAO */

/* PROCEDURES JÁ CRIADAS E ARMAZENADAS NO SISTEMA */

SP_COLUMNS ALUNO
GO

SP_HELP ALUNO
GO

/* INSERINDO DADOS */

INSERT INTO ALUNO VALUES('ANDRE','M','1982/08/09','ANDRE@IG.COM')
INSERT INTO ALUNO VALUES('ANA','F','2004/06/30','ANA@IG.COM')
INSERT INTO ALUNO VALUES('RUI','M','1972/05/26','RUI@IG.COM')
INSERT INTO ALUNO VALUES('JOHN JONES','M','1986/4/10','JOHNJONES@IG.COM')
GO

SELECT * FROM ALUNO
GO
/* INSERTS PARA ENDERECO */


INSERT INTO ENDERECO VALUES('FLAMENGO', 'RJ', 1)
INSERT INTO ENDERECO VALUES('CENTRO', 'SP', 2)
INSERT INTO ENDERECO VALUES('MORUMBI', 'SP', 3)
INSERT INTO ENDERECO VALUES('CENTRO', 'MG', 4)
GO
/* CRIANDO TABELA TELEFONE */
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	CHECK (TIPO IN('RES','COM', 'CEL')),
	NUMERO VARCHAR(10),
	ID_ALUNO INT,
)
GO

INSERT INTO TELEFONE VALUES('CEL', '7899899', 2)
INSERT INTO TELEFONE VALUES('RES', '684563', 2)
INSERT INTO TELEFONE VALUES('COM', '4564786', 3)
INSERT INTO TELEFONE VALUES('CEL', '8696954', 3)
GO

/* PEGAR DATA ATUAL */

SELECT GETDATE()
GO

/* CLAUSULA AMBIGUA */

SELECT A.NOME,
	   ISNULL(T.TIPO, 'SEM') AS "TIPO",
	   ISNULL(T.NUMERO,'NUMERO') AS "TELEFONE",
	   E.BAIRRO,
	   E.UF
FROM ALUNO A
	LEFT JOIN TELEFONE T
	ON A.IDALUNO = T.ID_ALUNO
	INNER JOIN ENDERECO E
	ON A.IDALUNO = E.ID_ALUNO
GO

/* DATAS */

SELECT NOME, NASCIMENTO
FROM ALUNO
GO


/* FUNCAO GETDATE() TRAZ DIA E HORA */

SELECT NOME, GETDATE() AS DIA_HORA FROM ALUNO
GO

/* DATADIFF - CALCULA A DIFERENÇA ENTRE 2 DATAS */
SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()) AS "IDADE"
FROM ALUNO 
GO  

SELECT NOME, DATEDIFF(MONTH, NASCIMENTO, GETDATE()) AS "IDADE"
FROM ALUNO 
GO  

SELECT NOME, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS "IDADE"
FROM ALUNO 
GO  

/* DATENAME - TRAZ O NOME DA PARTE DA DATA EM QUESTAO */
SELECT NOME, DATENAME(MONTH, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, DATENAME(YEAR, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO)
FROM ALUNO
GO

/* DATEPART - POREM O RETORNO É UM INTEIRO */

SELECT NOME, DATEPART(MONTH, NASCIMENTO)
FROM ALUNO
GO

/* DATEADD - RETORNA UMA DATA SOMANDO A OUTRA DATA*/

SELECT DATEADD(YEAR, 20, GETDATE());
GO

/* CONVERSAO DE DADOS */

/*CAST - CONVERTE UMA STRING PARA NUMERICO 
*/

SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO
 
--https://learn.microsoft.com/pt-br/sql/t-sql/data-types/data-type-conversion-database-engine?view=sql-server-ver16

/* CONVERSAO E CONCATENACAO */

SELECT NOME,
DAY(NASCIMENTO)
FROM ALUNO
GO

/* MODELO BRASILEIRO EXERCICIO */
SELECT NOME,
      CAST(DAY(NASCIMENTO) AS VARCHAR) +
'/' + CAST(MONTH(NASCIMENTO) AS VARCHAR) +
'/' + CAST(YEAR(NASCIMENTO) AS VARCHAR) AS "NASCIMENTO"
FROM ALUNO
GO

/* CHARINDEX - RETORNA UM INTEIRO */

SELECT NOME, CHARINDEX('A',NOME) AS INDICE
FROM ALUNO
GO


SELECT NOME, CHARINDEX('A',NOME,2) AS INDICE
FROM ALUNO
GO

/* BULK INSERT - IMPORTACAO DE ARQUIVOS */

CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1) NOT NULL
)
GO

BULK INSERT LANCAMENTO_CONTABIL
FROM 'Z:\SCRIPTS\SQL SERVER\CONTAS.txt'
WITH 
(
	FIRSTROW = 2,
	DATAFILETYPE = 'CHAR',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO

/*EXERCICIO CHARINDEX*/
SELECT CONTA, VALOR,
CHARINDEX('D',DEB_CRED) AS DEBITO,
CHARINDEX('C',DEB_CRED) AS CREDITO,
CHARINDEX('C',DEB_CRED) * 2 - 1 AS MULTIPLICADOR
FROM LANCAMENTO_CONTABIL
GO

SELECT CONTA, SUM(VALOR * (CHARINDEX('C',DEB_CRED) * 2 - 1))  AS SALDO
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
ORDER BY CONTA
GO

/*TRIGGERS*/

CREATE TABLE PRODUTOS(
	IDPRODUTO INT PRIMARY KEY  IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CATEGORIA VARCHAR(30) NOT NULL,
	PRECO NUMERIC(10,2) NOT NULL
)
GO

CREATE TABLE HISTORICO(
	IDOPERACAO INT PRIMARY KEY IDENTITY,
	PRODUTO VARCHAR(50) NOT NULL,
	CATEGORIA VARCHAR(30) NOT NULL,
	PRECOANTIGO NUMERIC(10,2) NOT NULL,
	PRECONOVO NUMERIC(10,2) NOT NULL,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	MENSAGEM VARCHAR(100) 
)
GO

INSERT INTO PRODUTOS VALUES('LIVRO SQL SERVER', 'LIVROS', 98.00)
INSERT INTO PRODUTOS VALUES('LIVRO ORACLE', 'LIVROS', 50.00)
INSERT INTO PRODUTOS VALUES('CODIGO LIMPO', 'LIVROS', 80.00)
INSERT INTO PRODUTOS VALUES('LICENÇA POWERCENTER', 'SOFTWARE', 45000.00)
INSERT INTO PRODUTOS VALUES('NOTEBOOK I7', 'COMPUTADORES', 3200.00)
INSERT INTO PRODUTOS VALUES('LIVRO ARQUITETURA LIMPA', 'LIVRO', 90.00)
GO

/* VERIFICANDO USUARIOS */

SELECT SUSER_NAME()
GO

/* TRIGGER DE DADOS - DATA MANIPULATION LANGUAGE */

CREATE TRIGGER TRG_ATUALIZA_PRECO
ON DBO.PRODUTOS
FOR UPDATE AS
IF UPDATE(PRECO)
BEGIN
	DECLARE @IDPRODUTO INT
	DECLARE @PRODUTO VARCHAR(30)
	DECLARE @CATEGORIA VARCHAR(10)
	DECLARE @PRECO NUMERIC(10,2)
	DECLARE @PRECONOVO NUMERIC(10,2)
	DECLARE @DATA DATETIME
	DECLARE @USUARIO VARCHAR(30)
	DECLARE @MESNSAGEM VARCHAR(100)

	SELECT @IDPRODUTO = IDPRODUTO FROM INSERTED
	SELECT @PRODUTO = NOME FROM INSERTED
	SELECT @CATEGORIA = CATEGORIA FROM INSERTED
	SELECT @PRECO = PRECO FROM DELETED
	SELECT @PRECONOVO = PRECO FROM INSERTED

	SET @DATA = GETDATE()
	SET @USUARIO = SUSER_NAME()
	SET @MESNSAGEM = 'VALOR NÃO INSERIDO PELA TRIGGER TRG_ATUALIZA_PRECO'

	INSERT INTO HISTORICO
	(PRODUTO, CATEGORIA, PRECOANTIGO, PRECONOVO, DATA, USUARIO, MENSAGEM)
	VALUES 
	(@PRODUTO, @CATEGORIA, @PRECO, @PRECONOVO, @DATA, @USUARIO, @MESNSAGEM)

	PRINT 'TRIGGER EXECUTADA COM SUCESSO'
END
GO

/* EXECUTANDO UM UPDATE */

UPDATE PRODUTOS SET PRECO = 100.00
WHERE IDPRODUTO = 1
GO

SELECT * FROM PRODUTOS
SELECT * FROM HISTORICO
GO

DROP TRIGGER TRG_ATUALIZA_PRECO
GO

UPDATE PRODUTOS SET PRECO = 300.00
WHERE IDPRODUTO = 2
GO

UPDATE PRODUTOS SET NOME = 'LIVRO JAVASCRIPT'
WHERE IDPRODUTO = 2
GO 
SELECT * FROM HISTORICO
GO

/* VARIAVEIS DE SELECT */

CREATE TABLE RESULTADO(
	IDRESULTADO INT PRIMARY KEY IDENTITY,
	RESULTADO INT
)
GO

INSERT INTO RESULTADO VALUES((SELECT 10 + 10))
GO

/* ATRIBUINDO SELECTS  */
DECLARE
	@RESULTADO INT
	SET @RESULTADO = (SELECT 50 + 50)
	INSERT INTO RESULTADO VALUES(@RESULTADO)
	PRINT 'VALOR INSERIDO NA TABELA: ' + CAST(@RESULTADO AS VARCHAR)
GO 

/* TRIGGER UPDATE */
CREATE TABLE EMPREGADO(
	IDEMP INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30),
	SALARIO MONEY,
	IDGERENTE INT
)
GO

ALTER TABLE EMPREGADO 
ADD CONSTRAINT FK_GERENTE
FOREIGN KEY(IDGERENTE) REFERENCES EMPREGADO(IDEMP)
GO

INSERT INTO EMPREGADO VALUES ('CLARA', 5000.00, NULL)
INSERT INTO EMPREGADO VALUES ('CELIA', 4000.00, 1)
INSERT INTO EMPREGADO VALUES ('JONES', 4000.00, 1)
GO

CREATE TABLE HIST_SALARIO
(
	IDEMPREGADO INT,
	ANTIGOSAL MONEY,
	NOVOSAL MONEY,
	DATA DATETIME
)
GO

CREATE TRIGGER TRG_SALARIO
ON DBO.EMPREGADO
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
	INSERT INTO HIST_SALARIO
	(IDEMPREGADO, ANTIGOSAL, NOVOSAL,DATA)
	SELECT D.IDEMP, D.NOME, D.SALARIO, I.SALARIO, GETDATE()
	FROM DELETED D, INSERTED I
	WHERE D.IDEMP = I.IDEMP


END
GO

UPDATE EMPREGADO SET SALARIO = SALARIO * 1.1
GO

SELECT * FROM HIST_SALARIO
GO

/* SALARIO ANTIGO, NOVO, DATA E NOME DO EMPREGO */

CREATE TABLE SALARIO_RANGE(
	MINSAL MONEY,
	MAXSAL MONEY,
)
GO

INSERT INTO SALARIO_RANGE VALUES(2000.00, 6000.00)
GO

CREATE TRIGGER TRG_RANGE
ON DBO.EMPREGADO
FOR INSERT, UPDATE AS
	DECLARE
		@MINSAL MONEY,
		@MAXSAL MONEY,
		@ATUALSAL MONEY
	
	SELECT @MINSAL = MINSAL, @MAXSAL = MAXSAL FROM SALARIO_RANGE

	SELECT @ATUALSAL = I.SALARIO
	FROM INSERTED I

	IF(@ATUALSAL < @MINSAL)
	BEGIN
		RAISERROR('SALARIO MENOR QUE O PISO', 16,1)
		ROLLBACK TRANSACTION
	END

	IF(@ATUALSAL > @MAXSAL)
	BEGIN
		RAISERROR('SALARIO MAIOR QUE O TETO', 16,1)
		ROLLBACK TRANSACTION
	END
GO

UPDATE EMPREGADO SET SALARIO = 9000.00
WHERE IDEMP = 1
GO

UPDATE EMPREGADO SET SALARIO = 1000.00
WHERE IDEMP = 1
GO

UPDATE EMPREGADO SET SALARIO = 3000.00
WHERE IDEMP = 1
GO

SELECT * FROM EMPREGADO
GO

/* VERIFICANDO O TEXTO DA UMA TRIGGER */

SP_HELPTEXT TRG_RANGE
GO