/*CARDINALIDADE*/

/*QUEM DECIDE A CARDINALIDADE E A REGRA DE NEGOCIOS*/

/*PRIMEIRO ALGARISMO - OBRIGATORIEDADE
0 - NÃO OBRIGATORIO
1 - OBRIGATORIO 

SEGUNDO ALGARISMO - CARDINALIDADE
1 - MÁXIMO DE UM
N - MAIS QUE UM
*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR (30) NOT NULL,
	UF CHAR (2),
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT, 
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/*ENDERECO - OBRIGATORIO
CADASTRO DE SOMENTE UM

TELEFONE - NAO OBRIGATORIO 
CADASTRO DE MAIS DE UM (OPCIONAL)
*/

/* EM RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */ 

/* EM RELACIONAMENTOS 1 X N A CHAVE ESTRANGEIRA FICA NA CARDINALIDADE N */ 

INSERT INTO CLIENTE VALUES (NULL, 'JOAO', 'M', 'JOAO@GMAIL.COM', '867455456');
INSERT INTO CLIENTE VALUES (NULL, 'PELE', 'M', 'PELE@GMAIL.COM', '9645852');
INSERT INTO CLIENTE VALUES (NULL, 'ANA', 'F', 'ANA@GMAIL.COM', '58723549826');
INSERT INTO CLIENTE VALUES (NULL, 'NAMI', 'F', 'NAMI@GMAIL.COM', '44758648896');
INSERT INTO CLIENTE VALUES (NULL, 'IRINEU', 'M', 'IRINEU@GMAIL.COM', '1991849568');
INSERT INTO CLIENTE VALUES (NULL, 'GABY', 'F', 'GABY@GMAIL.COM', '6546541654');
INSERT INTO CLIENTE VALUES (NULL, 'ZORO', 'M', NULL, '353445356');

SELECT * FROM CLIENTE;

+-----------+--------+------+------------------+-------------+
| IDCLIENTE | NOME   | SEXO | EMAIL            | CPF         |
+-----------+--------+------+------------------+-------------+
|         1 | JOAO   | M    | JOAO@GMAIL.COM   | 867455456   |
|         2 | PELE   | M    | PELE@GMAIL.COM   | 9645852     |
|         3 | ANA    | F    | ANA@GMAIL.COM    | 58723549826 |
|         4 | NAMI   | F    | NAMI@GMAIL.COM   | 44758648896 |
|         5 | IRINEU | M    | IRINEU@GMAIL.COM | 1991849568  |
|         6 | GABY   | F    | GABY@GMAIL.COM   | 6546541654  |
|         8 | ZORO   | M    | NULL             | 353445356   |
+-----------+--------+------+------------------+-------------+

INSERT INTO ENDERECO VALUES(NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HERIZONTE', 'MG', 5);
INSERT INTO ENDERECO VALUES(NULL, 'RUA CAPITAO HERMES', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 2);
INSERT INTO ENDERECO VALUES(NULL, 'RUA PRES VARGAS', 'JARDINS', 'SAO PAULO', 'SP', 1);
INSERT INTO ENDERECO VALUES(NULL, 'RUA ALFANDEGA', 'ESTACIO', 'RIO DE JANEIRO', 'RJ', 4);
INSERT INTO ENDERECO VALUES(NULL, 'RUA DO OUVIDOR', 'FLAMENGO', 'RIO DE JANEIRO', 'RJ', 6);
INSERT INTO ENDERECO VALUES(NULL, 'RUA URUGUAIANA', 'CENTRO', 'VITORIA', 'ES', 3);
INSERT INTO ENDERECO VALUES(NULL, 'RUA LIBERDADE', 'CENTRO', 'SAO PAULO', 'SP', 8);


