CREATE DATABASE OFICINA_CORRETO;

USE OFICINA_CORRETO;

/* CRIANDO TABELAS */
CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F'),
    ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL'),
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT
);

CREATE TABLE MARCA(
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) UNIQUE
);  

CREATE TABLE CARRO(
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) NOT NULL,
    PLACA VARCHAR(30) NOT NULL UNIQUE,
    ID_MARCA INT
);

CREATE TABLE TINTA(
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) UNIQUE
);

CREATE TABLE COR(
    ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY(ID_CARRO, ID_COR)
);

/*CONSTRAINTS E FOREIGN KEYS*/

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES TINTA(IDCOR);

ALTER TABLE COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

/* PREENCHER O BANCO COM NO MINIMO 10 CLIENTES */
SHOW TABLES;

DESC CARRO;
DESC MARCA;
DESC TINTA;
DESC COR;
DESC CLIENTE;
DESC TELEFONE;

INSERT INTO MARCA VALUES (NULL,'Ford');
INSERT INTO MARCA VALUES (NULL,'Volkswagen');
INSERT INTO MARCA VALUES (NULL,'Chevrolet');
INSERT INTO MARCA VALUES (NULL,'Renault');
INSERT INTO MARCA VALUES (NULL,'Toyota');
INSERT INTO MARCA VALUES (NULL,'Fiat');
INSERT INTO MARCA VALUES (NULL,'Hyundai');
INSERT INTO MARCA VALUES (NULL,'Nissan');
INSERT INTO MARCA VALUES (NULL,'Dacia');
INSERT INTO MARCA VALUES (NULL,'Jeep');


INSERT INTO CARRO VALUES (NULL, 'Fiesta', 'ABC-1234', 1);
INSERT INTO CARRO VALUES (NULL,'Gol', 'DEF-5678', 2);
INSERT INTO CARRO VALUES (NULL,'Civic', 'GHI-9101', 3);
INSERT INTO CARRO VALUES (NULL,'Uno', 'JKL-2468', 4);
INSERT INTO CARRO VALUES (NULL,'Corolla', 'MNO-1357', 5);
INSERT INTO CARRO VALUES (NULL,'Palio', 'PQR-9876', 6);
INSERT INTO CARRO VALUES (NULL,'HB20', 'STU-6543', 7);
INSERT INTO CARRO VALUES (NULL,'Onix', 'VWX-2109', 8);
INSERT INTO CARRO VALUES (NULL,'Sandero', 'YZA-8432', 9);
INSERT INTO CARRO VALUES (NULL,'EcoSport', 'BDF-7531', 10);
UPDATE CARRO SET ID_MARCA = 3 WHERE IDCARRO = 8;

INSERT INTO TINTA VALUES (NULL,'vermelho');
INSERT INTO TINTA VALUES (NULL,'verde');
INSERT INTO TINTA VALUES (NULL,'azul');
INSERT INTO TINTA VALUES (NULL,'amarelo');
INSERT INTO TINTA VALUES (NULL,'preto');
INSERT INTO TINTA VALUES (NULL,'branco');
INSERT INTO TINTA VALUES (NULL,'laranja');
INSERT INTO TINTA VALUES (NULL,'roxo');
INSERT INTO TINTA VALUES (NULL,'rosa');
INSERT INTO TINTA VALUES (NULL,'marrom');

INSERT INTO COR VALUES (1, 2);
INSERT INTO COR VALUES (2, 2);
INSERT INTO COR VALUES (3, 3);
INSERT INTO COR VALUES (4, 4);
INSERT INTO COR VALUES (5, 5);
INSERT INTO COR VALUES (6, 6);
INSERT INTO COR VALUES (7, 7);
INSERT INTO COR VALUES (8, 8);
INSERT INTO COR VALUES (9, 9);
INSERT INTO COR VALUES (10, 10);

INSERT INTO CLIENTE VALUES (NULL,'João Silva', 'M', 1);
INSERT INTO CLIENTE VALUES (NULL,'Maria Santos', 'F', 2);
INSERT INTO CLIENTE VALUES (NULL,'Carlos Alberto', 'M', 3);
INSERT INTO CLIENTE VALUES (NULL,'Ana Beatriz', 'F', 4);
INSERT INTO CLIENTE VALUES (NULL,'José Luiz', 'M', 5);
INSERT INTO CLIENTE VALUES (NULL,'Juliana Pereira', 'F', 6);
INSERT INTO CLIENTE VALUES (NULL,'Lucas Ferreira', 'M', 7);
INSERT INTO CLIENTE VALUES (NULL,'Isabella Oliveira', 'F', 8);
INSERT INTO CLIENTE VALUES (NULL,'Pedro Henrique', 'M', 9);
INSERT INTO CLIENTE VALUES (NULL,'Manuela Silva', 'F', 10);

INSERT INTO TELEFONE VALUES (NULL,'RES', '1234567890', 1);
INSERT INTO TELEFONE VALUES (NULL,'CEL', '0987654321', 1);
INSERT INTO TELEFONE VALUES (NULL,'COM', '2345678901', 2);
INSERT INTO TELEFONE VALUES (NULL,'CEL', '1987654320', 2);
INSERT INTO TELEFONE VALUES (NULL,'RES', '3456789012', 3);
INSERT INTO TELEFONE VALUES (NULL,'COM', '2987654310', 4);
INSERT INTO TELEFONE VALUES (NULL,'CEL', '4567890123', 5);
INSERT INTO TELEFONE VALUES (NULL,'RES', '3987654321', 6);
INSERT INTO TELEFONE VALUES (NULL,'COM', '5678901234', 7);
INSERT INTO TELEFONE VALUES (NULL,'CEL', '4987654312', 8);

