/*FUNÇÕES DE AGREGAÇÃO*/ 

USE PROJETO;

/*CONTANDO REGISTROS DE UMA TABELA*/ 

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TABELA CLIENTE"
 FROM CLIENTE;
 
 /*OPERADOR GROUP BY*/
 
SELECT SEXO, COUNT(*)
FROM CLIENTE;

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

/*FUNCOES DE AGREGACAO PT II*/

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    JANEIRO FLOAT(10,2),
    FEVEREIRO FLOAT(10,2),
    MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES(NULL, 'CARLOS', 'M', 946565.45, 657865.47, 753487.86);
INSERT INTO VENDEDORES VALUES(NULL, 'PAULA', 'F', 8465765.21, 758769.98, 64499784.58);
INSERT INTO VENDEDORES VALUES(NULL, 'GARDEN', 'M', 18679.68, 87941.89, 865728.68);
INSERT INTO VENDEDORES VALUES(NULL, 'CICILIA', 'F', 847647.53, 688989.47, 35254.35);
INSERT INTO VENDEDORES VALUES(NULL, 'TOMAS', 'M', 453671.45, 569657.92, 987984.15);

/* MAX - TRAZ O VALOR MAXIMO DE UM COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_FEVEREIRO
FROM VENDEDORES;

/* MIN - TRAZ O VALOR MINIMO DE UM COLUNA */

SELECT MIN(FEVEREIRO) AS MAIOR_FEVEREIRO
FROM VENDEDORES;

/* AVG - TRAZ O VALOR MEDIO DE UM COLUNA */

SELECT AVG(FEVEREIRO) AS MAIOR_FEVEREIRO
FROM VENDEDORES;

/* VARIAS FUNCOES */

SELECT MAX(JANEIRO) AS MAXIMO_JANEIRO,
       MIN(JANEIRO) AS MINIMO_JANEIRO,
       AVG(MARCO) AS MEDIA_MARCO
FROM VENDEDORES;

/*TRUNCATE*/

SELECT MAX(JANEIRO) AS MAXIMO_JANEIRO,
       MIN(JANEIRO) AS MINIMO_JANEIRO,
       TRUNCATE(AVG(MARCO), 2) AS MEDIA_MARCO
FROM VENDEDORES;

/* AGREGANDO COM SUM */

SELECT SUM(JANEIRO) AS TOTAL_JANEIRO
FROM VENDEDORES;

SELECT SUM(JANEIRO) AS TOTAL_JANEIRO,
       SUM(FEVEREIRO) AS FEVEREIRO,
       SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES;

SELECT SEXO, SUM(MARCO) AS MARCO
FROM VENDEDORES
GROUP BY SEXO;
