/*FUNÇÕES DE AGREGAÇÃO*/ 

USE PROJETO;

/*CONTANDO REGISTROS DE UMA TABELA*/ 

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TABELA CLIENTE"
 FROM CLIENTE;
 
 /*OPERADOR GROUP BY*/
 
SELECT SEXO, COUNT(*)
FROM CLIENTE;

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;